/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MiCatalogoRouteImport } from './routes/mi-catalogo'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as ApiPublicOrdersRouteImport } from './routes/api/public/orders'
import { Route as ApiPublicNotifyPendingRouteImport } from './routes/api/public/notify-pending'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MiCatalogoRoute = MiCatalogoRouteImport.update({
  id: '/mi-catalogo',
  path: '/mi-catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrdersRoute = ApiPublicOrdersRouteImport.update({
  id: '/api/public/orders',
  path: '/api/public/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyPendingRoute = ApiPublicNotifyPendingRouteImport.update({
  id: '/api/public/notify-pending',
  path: '/api/public/notify-pending',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/acceso': typeof AccesoRoute
  '/mi-catalogo': typeof MiCatalogoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/m/$slug': typeof MSlugRoute
  '/api/public/notify-pending': typeof ApiPublicNotifyPendingRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/acceso': typeof AccesoRoute
  '/mi-catalogo': typeof MiCatalogoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/m/$slug': typeof MSlugRoute
  '/api/public/notify-pending': typeof ApiPublicNotifyPendingRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/acceso': typeof AccesoRoute
  '/mi-catalogo': typeof MiCatalogoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/m/$slug': typeof MSlugRoute
  '/api/public/notify-pending': typeof ApiPublicNotifyPendingRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/acceso'
    | '/mi-catalogo'
    | '/sitemap.xml'
    | '/m/$slug'
    | '/api/public/notify-pending'
    | '/api/public/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/acceso'
    | '/mi-catalogo'
    | '/sitemap.xml'
    | '/m/$slug'
    | '/api/public/notify-pending'
    | '/api/public/orders'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/acceso'
    | '/mi-catalogo'
    | '/sitemap.xml'
    | '/m/$slug'
    | '/api/public/notify-pending'
    | '/api/public/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AccesoRoute: typeof AccesoRoute
  MiCatalogoRoute: typeof MiCatalogoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MSlugRoute: typeof MSlugRoute
  ApiPublicNotifyPendingRoute: typeof ApiPublicNotifyPendingRoute
  ApiPublicOrdersRoute: typeof ApiPublicOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-catalogo': {
      id: '/mi-catalogo'
      path: '/mi-catalogo'
      fullPath: '/mi-catalogo'
      preLoaderRoute: typeof MiCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orders': {
      id: '/api/public/orders'
      path: '/api/public/orders'
      fullPath: '/api/public/orders'
      preLoaderRoute: typeof ApiPublicOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-pending': {
      id: '/api/public/notify-pending'
      path: '/api/public/notify-pending'
      fullPath: '/api/public/notify-pending'
      preLoaderRoute: typeof ApiPublicNotifyPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AccesoRoute: AccesoRoute,
  MiCatalogoRoute: MiCatalogoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MSlugRoute: MSlugRoute,
  ApiPublicNotifyPendingRoute: ApiPublicNotifyPendingRoute,
  ApiPublicOrdersRoute: ApiPublicOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
